PositionMgt User cases
CSC207-2022F-UofT/course-project-insane-hr-system pull request #33
Opened 2022-11-20 05:32 UTC by staceylry

plz point out any problem that i can improve, thx!!

2022-11-20 16:49 UTC, kaizen-w requested changes
The basic structure looks ok. One suggestion I can add is that the gateway should check if the employee is in the Database. Also, I believe that you are missing import statements. I'm also a little confused as to how the save method works. I believe that you are trying to save data in the Interactor?  I think that your goal here was to save data in the Response Model to the Database. The request model should be created by the controller rather than the Interactor and it would be better to create a response model in the Interactor, pass it to the gateway to save the data in the response in the database.

2022-11-20 16:51 UTC, zeyuzhang516 approved these changes

2022-11-20 19:05 UTC, tlan4 requested changes

2022-11-20 19:05 UTC, tlan4 commented on src/main/java/PositionMgt/PositionMgtInputBoundary.java
> +    PositionMgtRequestModel create(PositionMgtRequestModel requestModel);
As in the return type should response model

2022-11-21 06:32 UTC, staceylry commented on src/main/java/PositionMgt/PositionMgtInputBoundary.java
> +    PositionMgtRequestModel create(PositionMgtRequestModel requestModel);
thx! I just fixed this problem

2022-11-21 06:33 UTC, staceylry commented
> The basic structure looks ok. One suggestion I can add is that the gateway should check if the employee is in the Database. Also, I believe that you are missing import statements. I'm also a little confused as to how the save method works. I believe that you are trying to save data in the Interactor? I think that your goal here was to save data in the Response Model to the Database. The request model should be created by the controller rather than the Interactor and it would be better to create a response model in the Interactor, pass it to the gateway to save the data in the response in the database.

thx! I just modified this to make it better

2022-11-23 17:49 UTC, KunLW approved these changes

2022-12-08 03:34 UTC, kaizen-w approved these changes

2022-12-08 15:39 UTC, zeyuzhang516 approved these changes

2022-12-09 01:26 UTC, lungerjo approved these changes

2022-12-09 17:35 UTC, closed without merging