feature 4 employee enrollment Update
CSC207-2022F-UofT/course-project-insane-hr-system pull request #45
Opened 2022-11-22 03:04 UTC by zeyuzhang516

Update the controller and gateway for clean architecture;
Remove the unimplemented feature (add_department, delete_employee)
Add UI for employee enrollment

2022-11-22 03:11 UTC, GitHaoBao approved these changes

2022-11-22 03:39 UTC, tlan4 requested changes
Should put controllers in controller package. Rename presenters to outputboundary. Rename responseformatter to presenter and put them in the presenter package. Put ui stuff in ui package.

2022-11-22 18:43 UTC, tlan4 approved these changes

2022-11-22 23:32 UTC, staceylry approved these changes

2022-11-23 00:49 UTC, KunLW approved these changes

2022-11-23 00:49 UTC, merged